// Libraries
import { createContext, useContext, useState } from "react";

const LanguageContext = createContext(undefined);

const translations = {
  uz: {
    // Header
    "nav.about": "Haqida",
    "nav.features": "Xususiyatlar",
    "nav.contact": "Aloqa",
    "nav.login": "Kirish",
    "nav.signup": "Ro'yxatdan o'tish",
    "nav.logout": "Chiqish",

    // Home page
    "home.title": "IlmHub o'quv markazi",
    "home.subtitle":
      "Ta'limga zamonaviy yondashuvlar. Ingliz tili, IT, Matematika va eng zamonaviy kurslarimiz bir maydonda o'rganish imkoniyati. Farzandingiz kelajagini birgalikda ilmhubda quramiz!",
    "home.phone": "94 671 50 60",
    "home.contact_button": "Ma'lumot olish",
    "home.register_text": "Registratsiya uchun",
    "home.call_now": "hoziroq qo'ng'iroq qiling",
    "home.why_choose": "Nima uchun IlmHub?",
    "home.feature1_title": "Tajribali o‘qituvchilar",
    "home.feature1_desc": "Malakali va tajribali ustozlar",
    "home.feature2_title": "Zamonaviy dastur",
    "home.feature2_desc": "Eng so‘nggi kurslar va materiallar",
    "home.feature3_title": "Tanga tizimi",
    "home.feature3_desc": "Mukofot asosidagi o‘quv tizimi",
    "home.stats_students": "O‘quvchilar",
    "home.stats_teachers": "O‘qituvchilar",
    "home.stats_courses": "Kurslar",
    "home.stats_success": "Muvaffaqiyat darajasi",
    "home.cta_title": "O‘quv safaringizni boshlashga tayyormisiz?",
    "home.cta_subtitle": "Biz bilan birga o‘qiyotgan minglab talabalar safiga qo‘shiling.",
    "home.learn_more": "Batafsil ma'lumot",

    // About page
    "about.title": "Biz haqimizda",
    "about.description":
      "IlmHub - zamonaviy ta'lim markazidir. Biz o'quvchilarga yuqori sifatli ta'lim berish va ularning kelajagini shakllantirishga yordam beramiz.",
    "about.mission_title": "Bizning Missiyamiz",
    "about.mission_desc": "Yuqori sifatli ta'lim berish va talabalarni kelajakdagi muvaffaqiyatlari uchun bilim va ko'nikmalar bilan quvvatlantirish.",
    "about.vision_title": "Bizning Vizyonimiz",
    "about.vision_desc": "O'zbekistonda yetakchi ta'lim markaziga aylanish, innovatsiyalar va o'qishda mukammallikka intilish.",
    "about.values_title": "Bizning Qadriyatlarimiz",
    "about.values_desc": "Mukammallik, halollik, innovatsiyalar va talaba markazida bo'lish bizning asosiy qadriyatlarimizdir.",

    "about.achievements_title": "Yutuqlarimiz",
    "about.achievement1_title": "500+ bitiruvchilar",
    "about.achievement1_desc": "500 dan ortiq talabalar muvaffaqiyatli o‘qitildi va bitirdi",
    "about.achievement2_title": "20+ ta kurslar",
    "about.achievement2_desc": "Turli fanlarni qamrab olgan keng qamrovli dastur",
    "about.achievement3_title": "95% muvaffaqiyat darajasi",
    "about.achievement3_desc": "Talabalar natijalarida yuqori muvaffaqiyat ko‘rsatkichi",
    "about.achievement4_title": "Xalqaro standartlar",
    "about.achievement4_desc": "Ta’limda xalqaro eng yaxshi amaliyotlarga amal qilinadi",
    "about.team_title": "Bizning jamoamiz",
    "about.innovative_methods_title": "Innovatsion o‘qitish usullari",
    "about.innovative_methods_desc": "Zamonaviy va interaktiv ta’lim yondashuvlari",
    "about.experienced_faculty_title": "Tajribali o‘qituvchilar",
    "about.experienced_faculty_desc": "Malakali va tajribali ustozlar",
    "about.proven_results_title": "Isbotlangan natijalar",
    "about.proven_results_desc": "Yuqori muvaffaqiyat ko‘rsatkichlari va talabalar mamnuniyati",
    "about.international_standards_title": "Xalqaro standartlar",
    "about.international_standards_desc": "O‘quv dasturi global eng yaxshi amaliyotlarga moslashtirilgan",

    // Features page
    "features.title": "Xususiyatlar",
    "features.subtitle": "IlmHub Coinni mukammal ta’lim platformasiga aylantiradigan kuchli xususiyatlarni kashf eting",
    "features.admin_panel": "Admin paneli",
    "features.teacher_panel": "O'qituvchi paneli",
    "features.student_panel": "O'quvchi paneli",
    "features.coin_system": "Tanga tizimi",
    "features.multi_role": "Ko‘p rolli tizim",
    "features.coin_economy": "Tanga tizimi",
    "features.real_time": "Real vaqt rejimi",
    "features.admin_panel_desc": "To‘liq boshqaruv va ma’muriy imkoniyatlar",
    "features.teacher_management": "O‘qituvchilarni boshqarish",
    "features.teacher_management_desc": "O‘qituvchi akkauntlarini qo‘shish, tahrirlash va boshqarish",
    "features.item_management": "Mahsulotlarni boshqarish",
    "features.item_management_desc": "Talabalar xarid qilishi mumkin bo‘lgan do‘kon mahsulotlarini yaratish va boshqarish",
    "features.analytics_dashboard": "Analitika paneli",
    "features.analytics_dashboard_desc": "Batafsil hisobotlar va statistikani ko‘rish",
    "features.system_config": "Tizim sozlamalari",
    "features.system_config_desc": "Tizim sozlamalarini va parametrlarini boshqarish",
    "features.teacher_panel_desc": "O‘qituvchilar uchun o‘quvchilarni boshqarish va rag‘batlantirish vositalari",
    "features.student_management": "Talabalarni boshqarish",
    "features.student_management_desc": "Yangi talabalar qo‘shish va noyob 10 xonali ID yaratish",
    "features.coin_distribution": "Tanga tarqatish",
    "features.coin_distribution_desc": "Yutuqlar uchun talabalarni tangalar bilan rag‘batlantirish",
    "features.course_materials": "Kurs materiallari",
    "features.course_materials_desc": "Ta’limiy resurslarga kirish va ulashish",
    "features.student_progress": "Talabalar natijalari",
    "features.student_progress_desc": "Talabalar faoliyatini kuzatish va nazorat qilish",
    "features.student_panel_desc": "Talabalarni rag‘batlantiruvchi va qiziqarli xususiyatlar",
    "features.coin_wallet": "Tanga hamyoni",
    "features.coin_wallet_desc": "Tanga balansi va tranzaksiya tarixini ko‘rish",
    "features.shop_access": "Do‘konga kirish",
    "features.shop_access_desc": "O‘quv resurslari va mukofotlarni xarid qilish",
    "features.achievements": "Yutuqlar",
    "features.achievements_desc": "O‘qishdagi yutuqlar va bosqichlarni kuzatish",
    "features.learning_resources": "O‘quv resurslari",
    "features.learning_resources_desc": "Kurs materiallari va topshiriqlarga kirish",
    "features.more": "Tanga tizimi va boshqalar",
    "features.security": "Xavfsiz autentifikatsiya",
    "features.security_desc": "Ko‘p rolli xavfsiz tizim",
    "features.responsive": "Moslashuvchan dizayn",
    "features.responsive_desc": "Har qanday qurilmada mukammal ishlaydi — kompyuter, planshet, mobil",
    "features.realtime_updates": "Real vaqt yangilanishlari",
    "features.realtime_updates_desc": "Darhol xabarnomalar va jonli ma’lumotlar",
    "features.role_based": "Rolga asoslangan kirish",
    "features.role_based_desc": "Admin, o‘qituvchi va talabalar uchun turli interfeyslar",
    "features.cta_title": "Ushbu imkoniyatlarni sinab ko‘rishga tayyormisiz?",
    "features.cta_desc": "Bugunoq qo‘shiling va bizning innovatsion platformamiz qanday qilib sizning ta’lim tajribangizni o‘zgartirishi mumkinligini bilib oling.",
    "features.secure_reliable": "Xavfsiz va ishonchli",
    "features.multi_role_support": "Ko‘p rolli qo‘llab-quvvatlash",
    "features.reward_system": "Rag‘batlantiruvchi tanga tizimi",

    // Contact page
    "contact.title": "Aloqa",
    "contact.address": "Manzil",
    "contact.phone": "Telefon",
    "contact.email": "Email",
    "contact.subtitle": "Biz bilan bog‘laning. Biz sizga ta’lim safaringizda yordam beramiz.",
    "contact.available_languages": "O‘zbek va Ingliz tillarida mavjud",
    "contact.info_title": "Aloqa ma’lumotlari",
    "contact.info_desc": "Biz bilan bog‘lanishning bir nechta usullari mavjud",
    "contact.address_full": "Toshkent, Yunusobod tumani, Abdulla Qahhor ko‘chasi 1A",
    "contact.metro": "Metro bekati: Yunusobod, 5 daqiqalik yurish masofasida",
    "contact.phone_number": "+998 94 671 50 60",
    "contact.phone_availability": "Talabalar uchun 24/7 yordam",
    "contact.email_address": "info@ilmhub.uz",
    "contact.email_response": "Biz 24 soat ichida javob beramiz",
    "contact.working_hours": "Ish vaqti",
    "contact.working_days": "Dushanba - Shanba: 8:00 - 20:00",
    "contact.working_sunday": "Yakshanba: 9:00 - 18:00",
    "contact.form_title": "Bizga xabar yuboring",
    "contact.form_name": "Ism *",
    "contact.form_name_placeholder": "To‘liq ismingiz",
    "contact.form_phone": "Telefon",
    "contact.form_phone_placeholder": "+998 XX XXX XX XX",
    "contact.form_email": "Email *",
    "contact.form_email_placeholder": "your.email@example.com",
    "contact.form_subject": "Mavzu",
    "contact.form_subject_placeholder": "Bu nima haqida?",
    "contact.form_message": "Xabar *",
    "contact.form_message_placeholder": "Biz sizga qanday yordam bera olamiz...",
    "contact.form_send": "Xabar yuborish",
    "contact.visit_title": "Markazimizga tashrif buyuring",
    "contact.interactive_map": "Interaktiv xarita",
    "contact.visit_desc": "Yunusobod tumani, Toshkent. Bizning zamonaviy binomiz jamoat transportida qulay joylashgan va avtoturargoh mavjud.",
    "contact.follow_us": "Bizni kuzatib boring",
    "contact.follow_us_desc": "Yangiliklar, maslahatlar va ta’limiy kontentlar uchun ijtimoiy tarmoqlarda biz bilan bo‘ling.",
    "contact.faq_title": "Ko‘p beriladigan savollar",
    "contact.faq_q1": "Sizlar qaysi kurslarni taklif qilasizlar?",
    "contact.faq_a1": "Biz ingliz tili, IT, matematika va boshqa zamonaviy fanlar bo‘yicha kurslar taklif qilamiz. Dasturimiz xalqaro standartlarga moslashtirilgan.",
    "contact.faq_q2": "Tanga tizimi qanday ishlaydi?",
    "contact.faq_a2": "Talabalar yutuqlar va yaxshi natijalar uchun tangalar olishadi. Ushbu tangalar do‘kondan o‘quv materiallari va mukofotlarni xarid qilish uchun ishlatiladi.",
    "contact.faq_q3": "Qabul shartlari qanday?",
    "contact.faq_a3": "Biz barcha darajadagi talabalarni qabul qilamiz. Eng yaxshi kursni tanlash uchun biz bilan bog‘laning.",

    // Auth
    "auth.login": "Kirish",
    "auth.signup": "Ro'yxatdan o'tish",
    "auth.student_id": "O'quvchi ID",
    "auth.password": "Parol",
    "auth.email": "Email",
    "auth.name": "Ism",
    "auth.role": "Rol",
    "auth.admin": "Admin",
    "auth.teacher": "O'qituvchi",
    "auth.student": "O'quvchi",

    // Panels
    "admin.title": "Admin Paneli",
    "admin.add_teacher": "O'qituvchi qo'shish",
    "admin.add_item": "Mahsulot qo'shish",
    "admin.teachers": "O'qituvchilar",
    "admin.items": "Mahsulotlar",

    "teacher.title": "O'qituvchi Paneli",
    "teacher.add_student": "O'quvchi qo'shish",
    "teacher.give_coins": "Tanga berish",
    "teacher.students": "O'quvchilar",

    "student.title": "O'quvchi Paneli",
    "student.my_coins": "Mening tangalarim",
    "student.shop": "Do'kon",
    "student.buy": "Sotib olish",

    // Common
    "common.save": "Saqlash",
    "common.cancel": "Bekor qilish",
    "common.edit": "Tahrirlash",
    "common.delete": "O'chirish",
    "common.add": "Qo'shish",
    "common.name": "Nomi",
    "common.price": "Narxi",
    "common.coins": "Tangalar",
    "common.amount": "Miqdori",

    // Shop
    "shop.tshirt_title": "Cool T-Shirt Design",
    "shop.tshirt_desc": "Futbolka dizayni – chiroyli rang va grafika bilan",
    "shop.tshirt_price": "🪙 65",
    "shop.tshirt_stock": "10 ta mavjud",
    "shop.motivational_poster_title": "Motivatsion plakat",
    "shop.motivational_poster_desc": "Motivatsion sitata va zamonaviy dizayn",
    "shop.motivational_poster_price": "🪙 40",
    "shop.motivational_poster_stock": "5 ta mavjud",
    "shop.book_voucher_title": "Kitob kuponi",
    "shop.book_voucher_desc": "Kitob kuponi – ajoyib sovg'a",
    "shop.book_voucher_price": "🪙 100",
    "shop.book_voucher_stock": "3 ta mavjud",
    "shop.purchase": "Sotib olish",
  },
  en: {
    // Header
    "nav.about": "About",
    "nav.features": "Features",
    "nav.contact": "Contact",
    "nav.login": "Login",
    "nav.signup": "Sign Up",
    "nav.logout": "Logout",

    // Home page
    "home.title": "IlmHub Learning Center",
    "home.subtitle":
      "Modern approaches to education. English, IT, Mathematics and our most modern courses in one place. Let's build your child's future together at IlmHub!",
    "home.phone": "94 671 50 60",
    "home.contact_button": "Get Information",
    "home.register_text": "For registration",
    "home.call_now": "call now",
    "home.why_choose": "Why Choose IlmHub?",
    "home.feature1_title": "Expert Teachers",
    "home.feature1_desc": "Qualified and experienced instructors",
    "home.feature2_title": "Modern Curriculum",
    "home.feature2_desc": "Up-to-date courses and materials",
    "home.feature3_title": "Coin System",
    "home.feature3_desc": "Reward-based learning approach",
    "home.stats_students": "Students",
    "home.stats_teachers": "Teachers",
    "home.stats_courses": "Courses",
    "home.stats_success": "Success Rate",
    "home.cta_title": "Ready to Start Your Learning Journey?",
    "home.cta_subtitle": "Join thousands of students who are already learning with us.",
    "home.learn_more": "Learn More",

    "about.title": "About Us",
    "about.description":
      "IlmHub is a modern educational center. We help students receive high-quality education and shape their future.",
    "about.mission_title": "Our Mission",
    "about.mission_desc": "To provide high-quality education and empower students with knowledge and skills for their future success.",
    "about.vision_title": "Our Vision",
    "about.vision_desc": "To become the leading educational center in Uzbekistan, fostering innovation and excellence in learning.",
    "about.values_title": "Our Values",
    "about.values_desc": "Excellence, integrity, innovation, and student-centered approach guide everything we do.",

    "about.achievements_title": "Our Achievements",
    "about.achievement1_title": "500+ Students Graduated",
    "about.achievement1_desc": "Successfully trained and graduated over 500 students",
    "about.achievement2_title": "20+ Courses Available",
    "about.achievement2_desc": "Comprehensive curriculum covering various subjects",
    "about.achievement3_title": "95% Success Rate",
    "about.achievement3_desc": "High achievement rate in student outcomes",
    "about.achievement4_title": "International Standards",
    "about.achievement4_desc": "Following global best practices in education",
    "about.team_title": "Meet Our Team",
    "about.innovative_methods_title": "Innovative Teaching Methods",
    "about.innovative_methods_desc": "Modern and interactive approaches to learning",
    "about.experienced_faculty_title": "Experienced Faculty",
    "about.experienced_faculty_desc": "Qualified teachers with proven track records",
    "about.proven_results_title": "Proven Results",
    "about.proven_results_desc": "High success rates and student satisfaction",
    "about.international_standards_title": "International Standards",
    "about.international_standards_desc": "Curriculum aligned with global best practices",

    // Features page
    "features.title": "Features",
    "features.subtitle": "Discover the powerful features that make IlmHub Coin the perfect educational platform",
    "features.admin_panel": "Admin Panel",
    "features.teacher_panel": "Teacher Panel",
    "features.student_panel": "Student Panel",
    "features.coin_system": "Coin System",
    "features.multi_role": "Multi-role System",
    "features.coin_economy": "Coin Economy",
    "features.real_time": "Real-time",
    "features.admin_panel_desc": "Complete administrative control and management capabilities",
    "features.teacher_management": "Teacher Management",
    "features.teacher_management_desc": "Add, edit, and manage teacher accounts and permissions",
    "features.item_management": "Item Management",
    "features.item_management_desc": "Create and manage shop items that students can purchase",
    "features.analytics_dashboard": "Analytics Dashboard",
    "features.analytics_dashboard_desc": "View comprehensive reports and statistics",
    "features.system_config": "System Configuration",
    "features.system_config_desc": "Configure system settings and preferences",
    "features.teacher_panel_desc": "Comprehensive tools for educators to manage and engage students",
    "features.student_management": "Student Management",
    "features.student_management_desc": "Add new students and generate unique 10-digit IDs",
    "features.coin_distribution": "Coin Distribution",
    "features.coin_distribution_desc": "Reward students with coins for achievements",
    "features.course_materials": "Course Materials",
    "features.course_materials_desc": "Access and share educational resources",
    "features.student_progress": "Student Progress",
    "features.student_progress_desc": "Track and monitor student performance",
    "features.student_panel_desc": "Engaging features designed to motivate and reward learning",
    "features.coin_wallet": "Coin Wallet",
    "features.coin_wallet_desc": "View your coin balance and transaction history",
    "features.shop_access": "Shop Access",
    "features.shop_access_desc": "Purchase educational materials and rewards",
    "features.achievements": "Achievements",
    "features.achievements_desc": "Track your learning milestones and accomplishments",
    "features.learning_resources": "Learning Resources",
    "features.learning_resources_desc": "Access course materials and assignments",
    "features.more": "Coin System & More",
    "features.security": "Secure Authentication",
    "features.security_desc": "Multi-role authentication system with secure login",
    "features.responsive": "Responsive Design",
    "features.responsive_desc": "Works perfectly on all devices - desktop, tablet, mobile",
    "features.realtime_updates": "Real-time Updates",
    "features.realtime_updates_desc": "Instant notifications and live data synchronization",
    "features.role_based": "Role-based Access",
    "features.role_based_desc": "Different interfaces for admin, teachers, and students",
    "features.cta_title": "Ready to Experience These Features?",
    "features.cta_desc": "Join today and discover how our innovative platform can transform your learning experience.",
    "features.secure_reliable": "Secure & Reliable",
    "features.multi_role_support": "Multi-role Support",
    "features.reward_system": "Reward System",

    // Contact page
    "contact.title": "Contact",
    "contact.address": "Address",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.subtitle": "Get in touch with us. We're here to help you on your educational journey.",
    "contact.available_languages": "Available in Uzbek and English",
    "contact.info_title": "Contact Information",
    "contact.info_desc": "Multiple ways to reach us and get the information you need",
    "contact.address_full": "Tashkent, Yunusabad district, Abdulla Qahhor street 1A",
    "contact.metro": "Metro station: Yunusabad, 5 minutes walk",
    "contact.phone_number": "+998 94 671 50 60",
    "contact.phone_availability": "Available 24/7 for student support",
    "contact.email_address": "info@ilmhub.uz",
    "contact.email_response": "We respond within 24 hours",
    "contact.working_hours": "Working Hours",
    "contact.working_days": "Mon - Sat: 8:00 AM - 8:00 PM",
    "contact.working_sunday": "Sunday: 9:00 AM - 6:00 PM",
    "contact.form_title": "Send us a Message",
    "contact.form_name": "Name *",
    "contact.form_name_placeholder": "Your full name",
    "contact.form_phone": "Phone",
    "contact.form_phone_placeholder": "+998 XX XXX XX XX",
    "contact.form_email": "Email *",
    "contact.form_email_placeholder": "your.email@example.com",
    "contact.form_subject": "Subject",
    "contact.form_subject_placeholder": "What is this about?",
    "contact.form_message": "Message *",
    "contact.form_message_placeholder": "Tell us how we can help you...",
    "contact.form_send": "Send Message",
    "contact.visit_title": "Visit Our Center",
    "contact.interactive_map": "Interactive Map",
    "contact.visit_desc": "Located in the heart of Yunusabad district, our modern facility is easily accessible by public transport and has parking available.",
    "contact.follow_us": "Follow Us",
    "contact.follow_us_desc": "Stay connected with us on social media for updates, tips, and educational content.",
    "contact.faq_title": "Frequently Asked Questions",
    "contact.faq_q1": "What courses do you offer?",
    "contact.faq_a1": "We offer courses in English, IT, Mathematics, and other modern subjects. Our curriculum is designed to meet international standards.",
    "contact.faq_q2": "How does the coin system work?",
    "contact.faq_a2": "Students earn coins for achievements and good performance. These coins can be used to purchase educational materials and rewards from our shop.",
    "contact.faq_q3": "What are the admission requirements?",
    "contact.faq_a3": "We welcome students of all levels. Contact us for a consultation to determine the best course placement for your educational goals.",

    // Auth
    "auth.login": "Login",
    "auth.signup": "Sign Up",
    "auth.student_id": "Student ID",
    "auth.password": "Password",
    "auth.email": "Email",
    "auth.name": "Name",
    "auth.role": "Role",
    "auth.admin": "Admin",
    "auth.teacher": "Teacher",
    "auth.student": "Student",

    // Panels
    "admin.title": "Admin Panel",
    "admin.add_teacher": "Add Teacher",
    "admin.add_item": "Add Item",
    "admin.teachers": "Teachers",
    "admin.items": "Items",

    "teacher.title": "Teacher Panel",
    "teacher.add_student": "Add Student",
    "teacher.give_coins": "Give Coins",
    "teacher.students": "Students",

    "student.title": "Student Panel",
    "student.my_coins": "My Coins",
    "student.shop": "Shop",
    "student.buy": "Buy",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.add": "Add",
    "common.name": "Name",
    "common.price": "Price",
    "common.coins": "Coins",
    "common.amount": "Amount",

    // Shop
    "shop.tshirt_title": "Cool T-Shirt Design",
    "shop.tshirt_desc": "Cool T-shirt with vibrant colors and graphics",
    "shop.tshirt_price": "🪙 65",
    "shop.tshirt_stock": "10 in stock",
    "shop.motivational_poster_title": "Motivational Poster",
    "shop.motivational_poster_desc": "Motivational quote with modern design",
    "shop.motivational_poster_price": "🪙 40",
    "shop.motivational_poster_stock": "5 in stock",
    "shop.book_voucher_title": "Book Voucher",
    "shop.book_voucher_desc": "Book voucher — a perfect gift",
    "shop.book_voucher_price": "🪙 100",
    "shop.book_voucher_stock": "3 in stock",
    "shop.purchase": "Purchase",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("en");

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
